In [10]:
import numpy as np
bounds=np.ones((5,2))*np.array([[-np.inf,np.inf]])
bounds[1,1]=0
for i,item in enumerate(bounds):
    if (item==[-np.inf,np.inf]).any():
        print(item)

[-inf  inf]
[-inf   0.]
[-inf  inf]
[-inf  inf]
[-inf  inf]


### DeepPoly


In [3]:
from DeepPoly import DeepPoly 
solver=DeepPoly(12)
solver.addBoundInput(0,-1,1)
solver.addBoundInput(1,-1,1)
solver.addWeight(0,1.0,2)
solver.addWeight(1,1.0,2)
solver.addWeight(0,1.0,3)
solver.addWeight(1,-1.0,3)
solver.addWeight(4,1.0,6)
solver.addWeight(4,1.0,7)
solver.addWeight(5,1.0,6)
solver.addWeight(5,-1.0,7)
solver.addWeight(8,-1.0,10)
solver.addWeight(8,0.0,11)
solver.addWeight(9,1.0,10)
solver.addWeight(9,1.0,11)
solver.addWeight(12,-0.5,6)
solver.addReLU(2,4)
solver.addReLU(3,5)
solver.addReLU(6,8)
solver.addReLU(7,9)
solver.addWeight(12,3,10)
solver.addOutputProperty(11,1)
solver.addOutputProperty(10,-1)

In [4]:
solver.solve(0)

check 0
check 1
check 2
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
check 3
[ 1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
check 4
[0.5 0.5 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1. ]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
check 5
[ 0.5 -0.5  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   1. ]
[ 0. -0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
check 6
[1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.5]
[ 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  -0.5]
check 7
[0.5 0.5 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1. ]
[-0.5  0.5  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  -1. ]
check 8
[0.83333333 0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.41666667]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
check 9
[0.25 0.25 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   1.  ]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [5]:
from DeepPoly import DeepPoly
solver=DeepPoly(7)
solver.addWeight(0,1,2)
solver.addWeight(0,1,3)
solver.addWeight(1,1,2)
solver.addWeight(1,-1,2)
solver.addWeight(4,1,6)
solver.addWeight(5,-1,6)
solver.addReLU(2,4)
solver.addReLU(3,5)
solver.addBoundInput(0,-1,1)
solver.addBoundInput(1,-1,1)
solver.addOutputProperty(6,-1)
solver.addOutputProperty(7,-0.5)

In [6]:
solver.solve(0)

check 0
check 1
check 2
check 3
check 4
check 5
check 6
[[ 0.   0.   1.   1.   0.   0.   0. ]
 [ 0.   0.  -1.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.5  0.   0. ]
 [ 0.   0.   0.   0.   0.   0.5  0. ]
 [ 0.   0.   0.   0.   0.   0.   1. ]
 [ 0.   0.   0.   0.   0.   0.  -1. ]
 [ 0.   0.   0.   0.   0.   0.   0. ]
 [-1.  -1.   0.   0.   1.   0.5  0. ]]
[[-1.  1.]
 [-1.  1.]
 [-2.  2.]
 [-1.  1.]
 [ 0.  2.]
 [ 0.  1.]
 [-1.  2.]]
[ 0.   0.   0.   0.   0.   0.  -1.  -0.5]
[ 0.   0.   0.   0.  -1.   1.   0.  -0.5]
0.5
[ 0.   0.   0.   0.  -1.   1.   0.  -0.5]
[ 0.   0.   0.   0.   0.   1.   0.  -0.5]
[0.  0.  0.  0.5 0.  0.  0.  0. ]
0.5
[0.  0.  0.  0.5 0.  0.  0.  0. ]
[0.5 0.  0.  0.  0.  0.  0.  0. ]
0.5
not really unsat but you should change algorithm :>
0.5


In [ ]:
sum=0
